package io.spark.k8s.submit.service

import io.spark.k8s.submit.model.SparkSubmitRequest
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/**
 * E2E tests for Spark job submission using real Kubernetes API server.
 *
 * Test scenarios covered:
 * 1. Submit without pod templates
 * 2. Submit with driver and executor templates
 * 3. Submit with driver template only
 * 4. Submit with executor template only
 * 5. Concurrent submissions with resource isolation
 * 6. Custom namespace handling
 * 7. Template directory cleanup
 * 8. Custom driver pod name via spark config
 * 9. Custom app ID via spark config
 * 10. Auto-generated IDs when not configured
 * 11. Verify resources created by our code (ConfigMap volume, SPARK_CONF_DIR, namespace key)
 * 12. Verify owner references for garbage collection (ConfigMap, Service → Pod with controller=true)
 *
 * Note: Owner references with controller=true ensure automatic deletion of dependent resources
 * in real K8s clusters (via garbage collection controller). Test #12 validates this is set correctly.
 */
class SparkSubmitEndToEndTest extends AnyFlatSpec
  with Matchers
  with KubeAPIServerFixture {

  // Test constants
  private val SparkPiClass = "org.apache.spark.examples.SparkPi"
  private val SparkImage = "spark:3.5.5"
  private val LocalJar = "local:///opt/spark/examples/jars/spark-examples.jar"

  private lazy val DriverTemplateJson = loadPodTemplate("driver-template.json")
  private lazy val ExecutorTemplateJson = loadPodTemplate("executor-template.json")
  private lazy val DriverOnlyTemplateJson = loadPodTemplate("driver-only.json")
  private lazy val ExecutorOnlyTemplateJson = loadPodTemplate("executor-only.json")
  private lazy val SimpleTemplateJson = loadPodTemplate("simple-template.json")

  private val NoTemplateApp = "app-a"
  private val BothTemplatesApp = "app-b"
  private val DriverOnlyApp = "app-c"
  private val ExecutorOnlyApp = "app-d"
  private val ConcurrentApp1 = "app-e"
  private val ConcurrentApp2 = "app-f"
  private val NamespaceTestApp = "app-g"
  private val CleanupTestApp = "app-h"
  private val CustomPodNameApp = "app-i"
  private val CustomAppIdApp = "app-j"
  private val AutoGeneratedIdsApp = "app-k"
  private val VerifyCodeApp = "app-l"
  private val OwnerRefApp = "app-m"

  private val DriverOnlyLabel = "driver-only"
  private val TemplateLabelKey = "custom-label"
  private val TemplateLabelValue = "driver-template"
  private val PodKind = "Pod"

  private def createSubmitter(): SparkSubmitter = {
    val provider = new KubernetesClientProvider(() => getKubeClient)
    new SparkSubmitter(provider)
  }

  behavior of "Spark Job Submission End-to-End"

  it should "submit Spark job WITHOUT pod templates" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, NoTemplateApp,
      getTestNamespace, SparkImage, LocalJar)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe NoTemplateApp
    response.namespace shouldBe getTestNamespace
    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")
    response.sparkAppId.length should be > 10
    response.driverPodName should not be empty
    response.driverPodName should startWith(NoTemplateApp + "-")
    response.driverPodName should endWith("-driver")
    response.driverPodName.length should be > (NoTemplateApp.length + 8)

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe response.namespace
  }

  it should "submit Spark job WITH driver and executor pod templates" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, BothTemplatesApp,
      getTestNamespace, SparkImage, LocalJar)

    val request = SparkSubmitRequest(args, DriverTemplateJson, ExecutorTemplateJson)
    val response = submitter.submitJob(request)

    response should not be null
    response.appName shouldBe BothTemplatesApp
    response.namespace shouldBe getTestNamespace
    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")
    response.driverPodName should not be empty
    response.driverPodName should startWith(BothTemplatesApp)
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe response.namespace

    val podLabels = pod.getMetadata.getLabels
    podLabels should not be null
    if (podLabels.containsKey(TemplateLabelKey)) {
      podLabels.get(TemplateLabelKey) shouldBe TemplateLabelValue
    }
  }

  it should "submit Spark job WITH driver template ONLY" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, DriverOnlyApp,
      getTestNamespace, SparkImage, LocalJar)

    val request = SparkSubmitRequest(args, DriverOnlyTemplateJson, null)
    val response = submitter.submitJob(request)

    response should not be null
    response.appName shouldBe DriverOnlyApp
    response.namespace shouldBe getTestNamespace

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")

    response.driverPodName should not be empty
    response.driverPodName should startWith(DriverOnlyApp)
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe response.namespace

    val podLabels = pod.getMetadata.getLabels
    podLabels should not be null

    if (podLabels.containsKey(DriverOnlyLabel)) {
      podLabels.containsKey(DriverOnlyLabel) shouldBe true
    }
  }

  it should "submit Spark job WITH executor template ONLY" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, ExecutorOnlyApp,
      getTestNamespace, SparkImage, LocalJar)

    val request = SparkSubmitRequest(args, null, ExecutorOnlyTemplateJson)
    val response = submitter.submitJob(request)

    response should not be null
    response.appName shouldBe ExecutorOnlyApp
    response.namespace shouldBe getTestNamespace

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")

    response.driverPodName should not be empty
    response.driverPodName should startWith(ExecutorOnlyApp)
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe response.namespace
  }

  it should "handle CONCURRENT Spark application submissions with resource isolation" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl

    val args1 = buildSparkSubmitArgs(masterUrl, SparkPiClass, ConcurrentApp1,
      getTestNamespace, SparkImage, LocalJar)
    val args2 = buildSparkSubmitArgs(masterUrl, SparkPiClass, ConcurrentApp2,
      getTestNamespace, SparkImage, LocalJar)

    val response1 = submitter.submitJob(SparkSubmitRequest(args1))
    val response2 = submitter.submitJob(SparkSubmitRequest(args2))

    response1.appName shouldBe ConcurrentApp1
    response1.namespace shouldBe getTestNamespace
    response1.sparkAppId should startWith("spark-")
    response1.driverPodName should startWith(ConcurrentApp1)
    response1.driverPodName should endWith("-driver")

    response2.appName shouldBe ConcurrentApp2
    response2.namespace shouldBe getTestNamespace
    response2.sparkAppId should startWith("spark-")
    response2.driverPodName should startWith(ConcurrentApp2)
    response2.driverPodName should endWith("-driver")

    response1.sparkAppId should not equal response2.sparkAppId
    response1.driverPodName should not equal response2.driverPodName

    verifySparkResources(
      response1.driverPodName, response1.sparkAppId, getTestNamespace
    ) shouldBe true

    verifySparkResources(
      response2.driverPodName, response2.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod1 = getKubeClient.pods().inNamespace(getTestNamespace).withName(response1.driverPodName).get()
    val pod2 = getKubeClient.pods().inNamespace(getTestNamespace).withName(response2.driverPodName).get()

    pod1 should not be null
    pod2 should not be null
    pod1.getMetadata.getName shouldBe response1.driverPodName
    pod2.getMetadata.getName shouldBe response2.driverPodName
    pod1.getMetadata.getName should not equal pod2.getMetadata.getName

    val cm1 = findConfigMapByAppId(
      response1.sparkAppId, getTestNamespace
    )
    val cm2 = findConfigMapByAppId(
      response2.sparkAppId, getTestNamespace
    )

    cm1 should not be None
    cm2 should not be None
    cm1.get.getMetadata.getName should not equal cm2.get.getMetadata.getName
  }

  it should "use CUSTOM NAMESPACE from spark-submit args" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val customNamespace = "custom-namespace"

    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, NamespaceTestApp,
      customNamespace, SparkImage, LocalJar)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe NamespaceTestApp
    response.namespace shouldBe customNamespace

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")

    response.driverPodName should not be empty
    response.driverPodName should startWith(NamespaceTestApp)
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, customNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(customNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe customNamespace
  }

  it should "clean up template directories on successful submission" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, CleanupTestApp,
      getTestNamespace, SparkImage, LocalJar)

    val request = SparkSubmitRequest(args, SimpleTemplateJson, null)
    val response = submitter.submitJob(request)

    response should not be null
    response.appName shouldBe CleanupTestApp
    response.namespace shouldBe getTestNamespace

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")

    response.driverPodName should not be empty
    response.driverPodName should startWith(CleanupTestApp)
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName

    // This test verifies the submission completes successfully with template handling
  }

  it should "use CUSTOM DRIVER POD NAME when explicitly set in spark config" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val customDriverPodName = "my-custom-driver-pod"

    val additionalConf = Map(
      "spark.kubernetes.driver.pod.name" -> customDriverPodName
    )
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, CustomPodNameApp,
      getTestNamespace, SparkImage, LocalJar, additionalConf)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe CustomPodNameApp
    response.namespace shouldBe getTestNamespace

    response.driverPodName shouldBe customDriverPodName

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(customDriverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe customDriverPodName
    pod.getMetadata.getNamespace shouldBe getTestNamespace

    val service = findServiceByDriverPodName(customDriverPodName, getTestNamespace)
    service.foreach { svc =>
      svc.getMetadata.getName shouldBe s"$customDriverPodName-svc"
    }
  }

  it should "use CUSTOM APP ID when explicitly set in spark config" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val customAppId = "my-custom-app-id-123"

    val additionalConf = Map(
      "spark.app.id" -> customAppId
    )
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, CustomAppIdApp,
      getTestNamespace, SparkImage, LocalJar, additionalConf)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe CustomAppIdApp
    response.namespace shouldBe getTestNamespace

    response.sparkAppId shouldBe customAppId

    response.driverPodName should not be empty
    response.driverPodName should startWith(CustomAppIdApp + "-")
    response.driverPodName should endWith("-driver")

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
  }

  it should "AUTO-GENERATE both driver pod name and app ID when NOT set in config" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl

    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, AutoGeneratedIdsApp,
      getTestNamespace, SparkImage, LocalJar)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe AutoGeneratedIdsApp
    response.namespace shouldBe getTestNamespace

    response.sparkAppId should not be empty
    response.sparkAppId should startWith("spark-")
    response.sparkAppId.length should be > 10

    response.driverPodName should not be empty
    response.driverPodName should startWith(AutoGeneratedIdsApp + "-")
    response.driverPodName should endWith("-driver")
    response.driverPodName.length should be > (AutoGeneratedIdsApp.length + 8)

    verifySparkResources(
      response.driverPodName, response.sparkAppId, getTestNamespace
    ) shouldBe true

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe getTestNamespace
  }

  it should "verify resources created by our code (ConfigMap volume, SPARK_CONF_DIR, namespace key)" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, VerifyCodeApp,
      getTestNamespace, SparkImage, LocalJar)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe VerifyCodeApp

    verifyPodHasSparkConfDirEnv(response.driverPodName, getTestNamespace) shouldBe true
    verifyPodHasConfigMapVolumeMount(response.driverPodName, getTestNamespace) shouldBe true
    verifyPodHasConfigMapVolume(response.driverPodName, getTestNamespace) shouldBe true
    verifyConfigMapHasNamespaceKey(response.sparkAppId, getTestNamespace, getTestNamespace) shouldBe true
  }

  it should "set owner references for garbage collection (ConfigMap and Service reference driver Pod)" in {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, OwnerRefApp,
      getTestNamespace, SparkImage, LocalJar)

    val response = submitter.submitJob(SparkSubmitRequest(args))

    response should not be null
    response.appName shouldBe OwnerRefApp

    val configMap = findConfigMapByAppId(response.sparkAppId, getTestNamespace)
    configMap should not be None

    val configMapOwnerRefs = configMap.get.getMetadata.getOwnerReferences
    configMapOwnerRefs should not be null
    configMapOwnerRefs.isEmpty shouldBe false
    configMapOwnerRefs.get(0).getKind shouldBe PodKind
    configMapOwnerRefs.get(0).getName shouldBe response.driverPodName
    configMapOwnerRefs.get(0).getController shouldBe true

    val service = findServiceByDriverPodName(response.driverPodName, getTestNamespace)
    service should not be None

    val serviceOwnerRefs = service.get.getMetadata.getOwnerReferences
    serviceOwnerRefs should not be null
    serviceOwnerRefs.isEmpty shouldBe false
    serviceOwnerRefs.get(0).getKind shouldBe PodKind
    serviceOwnerRefs.get(0).getName shouldBe response.driverPodName
    serviceOwnerRefs.get(0).getController shouldBe true
  }
}
