package io.spark.k8s.submit.service

import io.spark.k8s.submit.model.{SparkSubmitRequest, SparkSubmitResponse}
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/**
 * E2E tests for Spark job submission using real Kubernetes API server.
 *
 * Test scenarios covered:
 * 1. Submit without pod templates
 * 2. Submit with driver and executor templates
 * 3. Submit with driver template only
 * 4. Submit with executor template only
 * 5. Concurrent submissions with resource isolation
 * 6. Custom namespace handling
 * 7. Template directory cleanup
 * 8. Custom driver pod name via spark config
 * 9. Custom app ID via spark config
 * 10. Auto-generated IDs when not configured
 * 11. Verify resources created by our code (ConfigMap volume, SPARK_CONF_DIR, namespace key)
 * 12. Verify owner references for garbage collection (ConfigMap, Service → Pod with controller=true)
 *
 * Note: Owner references with controller=true ensure automatic deletion of dependent resources
 * in real K8s clusters (via garbage collection controller). Test #12 validates this is set correctly.
 */
class SparkSubmitEndToEndTest extends AnyFlatSpec
  with Matchers
  with KubeAPIServerFixture {

  // Test constants
  private val SparkPiClass = "org.apache.spark.examples.SparkPi"
  private val SparkImage = "spark:3.5.5"
  private val LocalJar = "local:///opt/spark/examples/jars/spark-examples.jar"

  private lazy val DriverTemplateJson = loadPodTemplate("driver-template.json")
  private lazy val ExecutorTemplateJson = loadPodTemplate("executor-template.json")
  private lazy val DriverOnlyTemplateJson = loadPodTemplate("driver-only.json")
  private lazy val ExecutorOnlyTemplateJson = loadPodTemplate("executor-only.json")
  private lazy val SimpleTemplateJson = loadPodTemplate("simple-template.json")

  private val NoTemplateApp = "app-a"
  private val BothTemplatesApp = "app-b"
  private val DriverOnlyApp = "app-c"
  private val ExecutorOnlyApp = "app-d"
  private val ConcurrentApp1 = "app-e"
  private val ConcurrentApp2 = "app-f"
  private val NamespaceTestApp = "app-g"
  private val CleanupTestApp = "app-h"
  private val CustomPodNameApp = "app-i"
  private val CustomAppIdApp = "app-j"
  private val AutoGeneratedIdsApp = "app-k"
  private val VerifyCodeApp = "app-l"
  private val OwnerRefApp = "app-m"

  private val DriverOnlyLabel = "driver-only"
  private val TemplateLabelKey = "custom-label"
  private val TemplateLabelValue = "driver-template"
  private val PodKind = "Pod"

  private def createSubmitter(): SparkSubmitter = {
    val provider = new KubernetesClientProvider(() => getKubeClient)
    new SparkSubmitter(provider)
  }

  private def submitAndVerify(appName: String, namespace: String = getTestNamespace,
                              driverTemplate: String = null, executorTemplate: String = null,
                              additionalConf: Map[String, String] = Map.empty): SparkSubmitResponse = {
    val submitter = createSubmitter()
    val masterUrl = getKubeClient.getConfiguration.getMasterUrl
    val args = buildSparkSubmitArgs(masterUrl, SparkPiClass, appName, namespace, SparkImage, LocalJar, additionalConf)
    val request = SparkSubmitRequest(args, driverTemplate, executorTemplate)

    val response = submitter.submitJob(request)

    response should not be null
    response.appName shouldBe appName
    response.namespace shouldBe namespace
    response.sparkAppId should not be empty
    response.driverPodName should not be empty
    verifySparkResources(response.driverPodName, response.sparkAppId, namespace) shouldBe true

    val pod = getKubeClient.pods().inNamespace(namespace).withName(response.driverPodName).get()
    pod should not be null
    pod.getMetadata.getName shouldBe response.driverPodName
    pod.getMetadata.getNamespace shouldBe namespace

    response
  }

  private def getMasterUrl: String = getKubeClient.getConfiguration.getMasterUrl

  behavior of "Spark Job Submission End-to-End"

  it should "submit Spark job WITHOUT pod templates" in {
    submitAndVerify(NoTemplateApp)
  }

  it should "submit Spark job WITH driver and executor pod templates" in {
    val response = submitAndVerify(BothTemplatesApp, driverTemplate = DriverTemplateJson, executorTemplate = ExecutorTemplateJson)

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    val podLabels = pod.getMetadata.getLabels
    if (podLabels.containsKey(TemplateLabelKey)) {
      podLabels.get(TemplateLabelKey) shouldBe TemplateLabelValue
    }
  }

  it should "submit Spark job WITH driver template ONLY" in {
    val response = submitAndVerify(DriverOnlyApp, driverTemplate = DriverOnlyTemplateJson)

    val pod = getKubeClient.pods().inNamespace(getTestNamespace).withName(response.driverPodName).get()
    val podLabels = pod.getMetadata.getLabels
    if (podLabels.containsKey(DriverOnlyLabel)) {
      podLabels.containsKey(DriverOnlyLabel) shouldBe true
    }
  }

  it should "submit Spark job WITH executor template ONLY" in {
    submitAndVerify(ExecutorOnlyApp, executorTemplate = ExecutorOnlyTemplateJson)
  }

  it should "handle CONCURRENT submissions with resource isolation" in {
    val response1 = submitAndVerify(ConcurrentApp1)
    val response2 = submitAndVerify(ConcurrentApp2)

    response1.sparkAppId should not equal response2.sparkAppId
    response1.driverPodName should not equal response2.driverPodName

    val cm1 = findConfigMapByAppId(response1.sparkAppId, getTestNamespace)
    val cm2 = findConfigMapByAppId(response2.sparkAppId, getTestNamespace)
    cm1 should not be None
    cm2 should not be None
    cm1.get.getMetadata.getName should not equal cm2.get.getMetadata.getName
  }

  it should "use CUSTOM NAMESPACE from spark-submit args" in {
    submitAndVerify(NamespaceTestApp, namespace = "custom-namespace")
  }

  it should "clean up template directories on successful submission" in {
    submitAndVerify(CleanupTestApp, driverTemplate = SimpleTemplateJson)
  }

  it should "use CUSTOM DRIVER POD NAME when explicitly set in spark config" in {
    val customPodName = "custom-driver"
    val response = submitAndVerify(CustomPodNameApp, additionalConf = Map("spark.kubernetes.driver.pod.name" -> customPodName))

    response.driverPodName shouldBe customPodName

    val service = findServiceByDriverPodName(customPodName, getTestNamespace)
    service.foreach { svc =>
      svc.getMetadata.getName shouldBe s"$customPodName-svc"
    }
  }

  it should "use CUSTOM APP ID when explicitly set in spark config" in {
    val customAppId = "custom-id-123"
    val response = submitAndVerify(CustomAppIdApp, additionalConf = Map("spark.app.id" -> customAppId))

    response.sparkAppId shouldBe customAppId
  }

  it should "AUTO-GENERATE both driver pod name and app ID when NOT set in config" in {
    val response = submitAndVerify(AutoGeneratedIdsApp)

    response.sparkAppId.length should be > 10
    response.driverPodName should startWith(AutoGeneratedIdsApp + "-")
    response.driverPodName.length should be > (AutoGeneratedIdsApp.length + 8)
  }

  it should "verify resources created by our code (ConfigMap volume, SPARK_CONF_DIR, namespace key)" in {
    val response = submitAndVerify(VerifyCodeApp)

    verifyPodHasSparkConfDirEnv(response.driverPodName, getTestNamespace) shouldBe true
    verifyPodHasConfigMapVolumeMount(response.driverPodName, getTestNamespace) shouldBe true
    verifyPodHasConfigMapVolume(response.driverPodName, getTestNamespace) shouldBe true
    verifyConfigMapHasNamespaceKey(response.sparkAppId, getTestNamespace, getTestNamespace) shouldBe true
  }

  it should "set owner references for garbage collection (ConfigMap and Service reference driver Pod)" in {
    val response = submitAndVerify(OwnerRefApp)

    val configMap = findConfigMapByAppId(response.sparkAppId, getTestNamespace)
    configMap should not be None
    configMap.get.getMetadata.getOwnerReferences.get(0).getKind shouldBe PodKind
    configMap.get.getMetadata.getOwnerReferences.get(0).getName shouldBe response.driverPodName
    configMap.get.getMetadata.getOwnerReferences.get(0).getController shouldBe true

    val service = findServiceByDriverPodName(response.driverPodName, getTestNamespace)
    service should not be None
    service.get.getMetadata.getOwnerReferences.get(0).getKind shouldBe PodKind
    service.get.getMetadata.getOwnerReferences.get(0).getName shouldBe response.driverPodName
    service.get.getMetadata.getOwnerReferences.get(0).getController shouldBe true
  }
}
