sonar.projectKey=k8s-spark-submitter
sonar.projectName=k8s-spark-submitter
sonar.sources=src/main/scala
sonar.tests=src/test/scala
sonar.exclusions=**/target/**
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=target/surefire-reports

sonar.coverage.exclusions=\
    **/SparkSubmitServer.scala,\
    **/K8sSparkSubmitArgsParser.scala,\
    **/KubernetesClientProvider.scala,\
    **/Constants.scala,\
    **/ServerConfig.scala,\
    **/SparkSubmitException.scala,\
    **/model/*.scala
